package com.mealhunt.mealhunt;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.List;
/*
public class Profile {

    @SerializedName("name")
    @Expose
    private String name;

    @SerializedName("url")
    @Expose
    private String imageUrl;



    @SerializedName("location")
    @Expose
    private String location;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
}
*/
//
// Generated by JSON2Apex http://json2apex.herokuapp.com/
//

public class Profile {
    public Geometry geometry;
    public String icon;
    public String id;
    public String name;
    public Opening_hours opening_hours;
    public List<Photos> photos;
    public String place_id;
    public Integer price_level;
    public Double rating;
    public String reference;
    public String scope;
    public List<String> types;
    public String vicinity;

    public List<Photos> getPhotos() {
        return photos;
    }
    public String getName(){
        return name;
    }
    public String getVicinity(){
        return vicinity;
    }

    public class Geometry {
        public Location location;
        public Viewport viewport;
    }

    public class Photos {
        public Integer height;
        public List<String> html_attributions;
        public String photo_reference;
        public Integer width;

        public String getPhotoReference(){
            // https://maps.googleapis.com/maps/api/place/photo?photoreference=PHOTO_REFERENCE&maxheight=MAX_HEIGHT&maxwidth=MAX_WIDTH&key=YOUR_API_KEY
            String url = "https://maps.googleapis.com/maps/api/place/photo?photoreference=" + photo_reference
                    + "&maxheight=" + (height+1) + "&maxwidth=" + (width+1) +
                    "&key=" + "AIzaSyBynpSv6ecFaFMNsow2Ud86cMbL9MNBQpM";
            return url;
        }
    }


    public class Opening_hours {
        public Boolean open_now;
        public List<Html_attributions> weekday_text;
    }

    public class Viewport {
        public Location northeast;
        public Location southwest;
    }

    public class Html_attributions {
    }

    public class Location {
        public Double lat;
        public Double lng;
    }

}

